include:
  - board: xiao_ble//zmk
    shield: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n totem_left
  - board: xiao_ble//zmk
    shield: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n totem_right

  # Flash this instead of the above to "undongle," after a `settings_reset`.
  # - board: xiao_ble//zmk
  #   shield: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n totem_left
  # - board: xiao_ble//zmk
  #   shield: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n totem_right

  - board: xiao_ble//zmk
    shield: settings_reset

  - board: xiao_ble//zmk
    shield: totem_left_dongle prospector_adapter
